yolo_model:

  config_file:
    name: yolov3-bumblebee.cfg
  weight_file:
    name: yolov3-bumblebee_10000.weights
  threshold:
    value: 0.3
  detection_classes:
    names:
      - dice1
      - dice2
      - dice3
      - dice4
      - dice5
      - dice6
